### PR TITLE
Add "MLBox" python package

### PR DESCRIPTION
**Pull request by AxeldeRomblay**
Hello ! 
I would like to add a package I have developed for auto-ML. I have already tested it on several Kaggle competitions and it works well :) 

--> github: https://github.com/AxeldeRomblay/MLBox
--> my Kaggle profile: https://www.kaggle.com/axelderomblay
--> PyPI : https://pypi.python.org/pypi/mlbox

Then I would like to write a kernel tuto on this competition: https://www.kaggle.com/c/nyc-taxi-trip-duration/discussion
Thank you !

### CODE REVIEW

**Comment by nerdcha** [comment]
Awesome, thanks, looking forward to seeing your tutorial!

**Comment by AxeldeRomblay** [comment]
Thanks ! But I have the following error when importing mlbox: 

`---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-4e0c3b5e221c> in <module>()
----> 1 from mlbox.preprocessing import *
      2 from mlbox.optimisation import *
      3 from mlbox.prediction import *

ModuleNotFoundError: No module named 'mlbox'`

Actually, it is not added to the list of available packages... 

`

import pip

for package in sorted(pip.get_installed_distributions(), key=lambda package: package.project_name):
    print("{} ({})".format(package.project_name, package.version))

`

**Comment by nerdcha** [comment]
I've temporarily reverted the change because `mlbox`'s requirement for an older Keras version seems to be breaking the build. Would you be able to flip it over to a `>= 2.0.2` instead of `== 2.0.2`?

```
Collecting mlbox
  Downloading mlbox-0.4.1.tar.gz
Collecting numpy>=1.13.0 (from mlbox)
  Downloading numpy-1.13.1-cp36-cp36m-manylinux1_x86_64.whl (17.0MB)
Requirement already satisfied: matplotlib>=2.0.2 in /opt/conda/lib/python3.6/site-packages (from mlbox)
Requirement already satisfied: hyperopt==0.1 in /opt/conda/lib/python3.6/site-packages (from mlbox)
Collecting ipyparallel==6.0.0 (from mlbox)
  Downloading ipyparallel-6.0.0-py2.py3-none-any.whl (190kB)
Collecting Keras==2.0.4 (from mlbox)
  Downloading Keras-2.0.4.tar.gz (199kB)
Requirement already satisfied: pandas>=0.18.0 in /opt/conda/lib/python3.6/site-packages (from mlbox)
Collecting scikit-learn==0.19b2 (from mlbox)
  Downloading scikit_learn-0.19b2-cp36-cp36m-manylinux1_x86_64.whl (11.7MB)
Requirement already satisfied: scipy>=0.17.0 in /opt/conda/lib/python3.6/site-packages (from mlbox)
Collecting Theano==0.9.0 (from mlbox)
  Downloading Theano-0.9.0.tar.gz (3.1MB)
Collecting xgboost==0.6a2 (from mlbox)
  Downloading xgboost-0.6a2.tar.gz (1.2MB)
Collecting lightgbm==2.0.2 (from mlbox)
  Downloading lightgbm-2.0.2-py2.py3-none-manylinux1_x86_64.whl (1.3MB)
Requirement already satisfied: six>=1.10 in /opt/conda/lib/python3.6/site-packages (from matplotlib>=2.0.2->mlbox)
Requirement already satisfied: python-dateutil in /opt/conda/lib/python3.6/site-packages (from matplotlib>=2.0.2->mlbox)
Requirement already satisfied: pytz in /opt/conda/lib/python3.6/site-packages (from matplotlib>=2.0.2->mlbox)
Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.6/site-packages (from matplotlib>=2.0.2->mlbox)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=1.5.6 in /opt/conda/lib/python3.6/site-packages (from matplotlib>=2.0.2->mlbox)
Requirement already satisfied: nose in /opt/conda/lib/python3.6/site-packages (from hyperopt==0.1->mlbox)
Requirement already satisfied: pymongo in /opt/conda/lib/python3.6/site-packages (from hyperopt==0.1->mlbox)
Requirement already satisfied: networkx in /opt/conda/lib/python3.6/site-packages (from hyperopt==0.1->mlbox)
Requirement already satisfied: future in /opt/conda/lib/python3.6/site-packages (from hyperopt==0.1->mlbox)
Requirement already satisfied: ipython-genutils in /opt/conda/lib/python3.6/site-packages (from ipyparallel==6.0.0->mlbox)
Requirement already satisfied: pyzmq>=13 in /opt/conda/lib/python3.6/site-packages (from ipyparallel==6.0.0->mlbox)
Requirement already satisfied: ipykernel in /opt/conda/lib/python3.6/site-packages (from ipyparallel==6.0.0->mlbox)
Requirement already satisfied: tornado>=4 in /opt/conda/lib/python3.6/site-packages (from ipyparallel==6.0.0->mlbox)
Requirement already satisfied: ipython>=4 in /opt/conda/lib/python3.6/site-packages (from ipyparallel==6.0.0->mlbox)
Requirement already satisfied: jupyter-client in /opt/conda/lib/python3.6/site-packages (from ipyparallel==6.0.0->mlbox)
Requirement already satisfied: decorator in /opt/conda/lib/python3.6/site-packages (from ipyparallel==6.0.0->mlbox)
Requirement already satisfied: pyyaml in /opt/conda/lib/python3.6/site-packages (from Keras==2.0.4->mlbox)
Requirement already satisfied: wheel in /opt/conda/lib/python3.6/site-packages (from lightgbm==2.0.2->mlbox)
Building wheels for collected packages: mlbox, Keras, Theano, xgboost
  Running setup.py bdist_wheel for mlbox: started
  Running setup.py bdist_wheel for mlbox: still running...
  Running setup.py bdist_wheel for mlbox: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/00/ab/26/c520a92c6df9b9c7c327cb99837431b22c9d30a67751fc0de5
  Running setup.py bdist_wheel for Keras: started
  Running setup.py bdist_wheel for Keras: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/48/82/42/f06a8c03a8f95ada523a81ba723e89f059693e6ad868d09727
  Running setup.py bdist_wheel for Theano: started
  Running setup.py bdist_wheel for Theano: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/d5/5b/93/433299b86e3e9b25f0f600e4e4ebf18e38eb7534ea518eba13
  Running setup.py bdist_wheel for xgboost: started
  Running setup.py bdist_wheel for xgboost: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/5e/c1/d6/522af54e5cc001fad4dd855117f8bf61b11d56443e06672e26
Successfully built mlbox Keras Theano xgboost
Installing collected packages: numpy, ipyparallel, Theano, Keras, scikit-learn, xgboost, lightgbm, mlbox
  Found existing installation: numpy 1.12.1
    Can't uninstall 'numpy'. No files were found to uninstall.
  Found existing installation: Theano 0.10.0.dev1
    Uninstalling Theano-0.10.0.dev1:
      Successfully uninstalled Theano-0.10.0.dev1
  Found existing installation: Keras 2.0.6
    Uninstalling Keras-2.0.6:
      Successfully uninstalled Keras-2.0.6
  Found existing installation: scikit-learn 0.20.dev0
    DEPRECATION: Uninstalling a distutils installed project (scikit-learn) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Can't uninstall 'scikit-learn'. No files were found to uninstall.
  Found existing installation: xgboost 0.6
    Uninstalling xgboost-0.6:
      Successfully uninstalled xgboost-0.6
  Found existing installation: lightgbm 2.0.4
    Uninstalling lightgbm-2.0.4:
      Successfully uninstalled lightgbm-2.0.4
Successfully installed Keras-2.0.4 Theano-0.9.0 ipyparallel-6.0.0 lightgbm-2.0.2 mlbox-0.4.1 numpy-1.13.1 scikit-learn-0.19b2 xgboost-0.6a2
Traceback (most recent call last):
  File "/opt/conda/bin/pip", line 6, in <module>
    sys.exit(pip.main())
  File "/opt/conda/lib/python3.6/site-packages/pip/__init__.py", line 249, in main
    return command.main(cmd_args)
  File "/opt/conda/lib/python3.6/site-packages/pip/basecommand.py", line 252, in main
    pip_version_check(session)
  File "/opt/conda/lib/python3.6/site-packages/pip/utils/outdated.py", line 102, in pip_version_check
    installed_version = get_installed_version("pip")
  File "/opt/conda/lib/python3.6/site-packages/pip/utils/__init__.py", line 838, in get_installed_version
    working_set = pkg_resources.WorkingSet()
  File "/opt/conda/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 644, in __init__
    self.add_entry(entry)
  File "/opt/conda/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 700, in add_entry
    for dist in find_distributions(entry, True):
  File "/opt/conda/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1949, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File "/opt/conda/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1463, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "/opt/conda/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1823, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "/opt/conda/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1703, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "/opt/conda/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1643, in load
    mtime = os.stat(path).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/opt/conda/lib/python3.6/site-packages/Keras-2.0.6-py3.6.egg'
```

**Comment by AxeldeRomblay** [comment]
Hum... I think you will probably have also some problem with the others packages (like lightgbm 2.0.4. ...). So I propose: 

`numpy>=1.13.0
matplotlib>=2.0.2
hyperopt>=0.1
ipyparallel>=6.0.0
Keras>=2.0.2
pandas>=0.18.0
scikit-learn>=0.19b2
scipy>=0.17.0
Theano>=0.9.0
xgboost>=0.6a2
lightgbm>=2.0.2` 

Are you OK with this changes ? Please tell me when MLBow will be re-added to the dockerfile :) 
Thank you very much ! 
Axel

**Comment by AxeldeRomblay** [comment]
MLBox's requirements are now updated on PyPI ! Please let me know if you still have some troubles... 
Thanks!

**Comment by nerdcha** [comment]
Cool, thanks for that! I just tried a `pip install mlbox && python -c 'import mlbox'` and that completed without error, so we should be all set now. I've kicked off another build from scratch, so assuming all goes well it should be live in about 90 minutes.

**Comment by AxeldeRomblay** [comment]
Great! thank you ! I'll let you know for the tuto !

**Pull request merged**
