### PR TITLE
removed fixing pillow to 9.5.0

### PR DESCRIPTION
**Pull request by aeozyalcin**
Update pillow to latest version so it can handle opening jpg images.

### CODE REVIEW

**Comment by calderjo** [comment]
cool! i pulled the image, seem to have the version you want!
let me run some test before i merge

**Review by calderjo — COMMENTED** [review]
LGTM

**Comment by aeozyalcin** [comment]
Thanks @calderjo. Any idea when I can take this image for a spin on Kaggle (aka i think it means when is the next release?)

**Comment by calderjo** [comment]
hard to say atm, we're pretty set on making the next release once we're able to get tf 2.17 installed, 
tf upgrades are always hard to estimates since a lot of things can go wrong.

**Pull request merged**
