### PR TITLE
Upgrade LightGBM to v3.1.1

### LINKED ISSUE #909: please bump LightGBM from 2.3.1 to 3.0.0
Hi- I would make a PR for this, but I wanted to check that this is something you would accept. There are quite a few improvements from the pinned version to 3.0.0. The version 2.3.1 is over a year old. Is there a reason it hasn't been updated? This is an extremely popular library on Kaggle.

### PR DESCRIPTION
**Pull request by rosbo**
Fixes #909.

Also updated the tests to load datasets from a csv file rather than a binary file. Using .csv files is more portable and avoid errors when changing versions:

```
lightgbm.basic.LightGBMError: Input file is not LightGBM binary file
```

BUG=175727746

### CODE REVIEW

**Comment by rosbo** [comment]
cc/ @marketneutral

**Review by Philmod — APPROVED** [review]

**Comment by marketneutral** [comment]
Thanks so much for this. I checked Kaggle today and I don't see that this has been deployed yet. Do you think this will be deployed before year end?

**Comment by Philmod** [comment]
> Thanks so much for this. I checked Kaggle today and I don't see that this has been deployed yet. Do you think this will be deployed before year end?

Hi @marketneutral, these changes won't be deployed before next year unfortunately.

**Comment by marketneutral** [comment]
Hi @Philmod ... would it be possible to release this to Kaggle notebooks this week? I'd like to use it in a current competition.

**Comment by rosbo** [comment]
Hi @marketneutral,

As soon as #932 is in. We will cut a new release. The release should be deployed to production this week.

Thank you

**Pull request merged**
