### PR TITLE
folium package

### PR DESCRIPTION
**Pull request by anirudhkm**
for map visualization!

### CODE REVIEW

**Comment by nerdcha** [comment]
Great, thanks for the suggestion!

**Comment by anirudhkm** [comment]
Hi, still I'm not able to import the folium package in Kaggle. What might be the reason for this?

Thank you

**Comment by nerdcha** [comment]
There's been a hiccup in our deployment pipeline that we're working around. It should be deployed shortly.

**Comment by nerdcha** [comment]
The package is now deployed. Thanks for your patience.

**Pull request merged**
