### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by ahmedbesbes**
add tqdm-keras

### CODE REVIEW

**Comment by nerdcha** [comment]
Do you mean `keras-tqdm`?

**Comment by ahmedbesbes** [comment]
yes sorry. 
pip install keras-tqdm
thank you

**Comment by nerdcha** [comment]
You need to fix the Dockerfile, then 😄

**Comment by crawforc3** [comment]
Closing because this conversation has gone stale

**Pull request closed without merging**
