### PR TITLE
Upgrade `torch` to `2.2.1` to resolve some issues

### PR DESCRIPTION
**Pull request by lh0x00**
Related issues were discussed: https://github.com/huggingface/transformers/issues/28731, https://github.com/Lightning-AI/litgpt/issues/327.

The solution used was to upgrade the `torch` version to `2.2.1` which is referenced [comment](https://github.com/huggingface/transformers/issues/28731#issuecomment-1918690108), and [colab release note](https://colab.research.google.com/notebooks/relnotes.ipynb#scrollTo=59f6f87f).

For example, some notebooks encountered the above problem and had to temporarily fix the error with the following code:

```python
import torch
torch.backends.cuda.enable_mem_efficient_sdp(False)
torch.backends.cuda.enable_flash_sdp(False)
```

- [Ghost 7B Alpha - Playground using Transformers, en](https://www.kaggle.com/code/lamhieu/ghost-7b-alpha-playground-using-transformers-en)
- [Ghost 7B Alpha - Playground using Transformers, vi](https://www.kaggle.com/code/lamhieu/ghost-7b-alpha-playground-using-transformers-vi)

### CODE REVIEW

**Comment by djherbis** [comment]
Thanks! It looks like its taking longer than 3hrs to build the torch files from source, I'll see if I can increase the timeout.

**Comment by djherbis** [comment]
@calderjo I filed b/337048719 internally for you to try and get that torch build to finish, thanks!

**Comment by calderjo** [comment]
>> I filed b/337048719 internally for you to try and get that torch build to finish, thanks!

on it, thanks

**Comment by lh0x00** [comment]
@calderjo @djherbis do I need to update anything else for this PR?

**Comment by djherbis** [comment]
Its still failing internal CI stuff, but I'm going to merge this and then test on the ci branch instead, thanks!

**Comment by lh0x00** [comment]
many thanks @djherbis !

**Comment by djherbis** [comment]
I had to pull this back:
https://github.com/Kaggle/docker-python/commit/67b4c134b7be8a849e5f08485a0b3e134e935771

Later versions of Torch are failing to build a wheel from source right now, but hopefully the next patch in June will fix that.

**Comment by lh0x00** [comment]
@djherbis I'm very sorry to hear this, I can't help because I can't see your internal jenkins. Hope you will handle it soon, thank you very much.

**Pull request merged**
