### PR TITLE
Upgrade to scikit-learn-intelex 2023.0.1

### PR DESCRIPTION
**Pull request by napetrov**
Defects have been addressed in latest version and it can be safely used

### CODE REVIEW

**Comment by napetrov** [comment]
@kaggleteam - can someone please assist here?

**Comment by napetrov** [comment]
@Borda @djherbis  - appreciate your help here

**Comment by djherbis** [comment]
@Borda I'm re-running ci on this since it seems to have failed the previous run by timeout.
I'm managing a bunch of high priority work right now so I haven't had a chance to review many PRs.
I'll try to set aside some time next week to review.

**Comment by napetrov** [comment]
> @Borda I'm re-running ci on this since it seems to have failed the previous run by timeout. I'm managing a bunch of high priority work right now so I haven't had a chance to review many PRs. I'll try to set aside some time next week to review.

Thanks. No worries. Just would like to see if there is anything i can fix and move forward. Will wait for your comments

**Comment by napetrov** [comment]
> @Borda I'm re-running ci on this since it seems to have failed the previous run by timeout. I'm managing a bunch of high priority work right now so I haven't had a chance to review many PRs. I'll try to set aside some time next week to review.

Looks rerun helped - any objections for integrating this?

**Pull request merged**
