### PR TITLE
Revert "add allennlp package"

### PR DESCRIPTION
**Pull request by Philmod**
Reverts Kaggle/docker-python#542

Because of a package version conflict.

Opened an issue #548 to track this.

### CODE REVIEW

**Comment by rosbo** [comment]
Can you keep the 5.3.0 base image and not install allennlp?

**Comment by Philmod** [comment]
Good call, done.

**Comment by Philmod** [comment]
I'm first going to try to not install the dependencies: https://github.com/Kaggle/docker-python/pull/550

**Comment by rosbo** [comment]
Feel free to submit this one first to fix the failing build

**Pull request merged**
