### PR TITLE
Update Dockerfile (pip install vtk)

### PR DESCRIPTION
**Pull request by paultimothymooney**
(pip install vtk)

### CODE REVIEW

**Comment by paultimothymooney** [comment]
The Visualization Toolkit (VTK) is an open-source, freely available software system for 3D computer graphics, modeling, image processing, volume rendering, scientific visualization, and information visualization. VTK also includes ancillary support for 3D interaction widgets, two- and three-dimensional annotation, and parallel computing. At its core, VTK is implemented as a C++ toolkit, requiring users to build applications by combining various objects into an application. The system also supports automated wrapping of the C++ core into Python, Java, and Tcl, so VTK applications may also be written using these interpreted programming languages.
VTK employs Kitware’s Quality Software Process (CMake, CTest, CDash, and CPack) to build, test, and package the system, making VTK a cross-platform application dependent on test-driven development and extreme programming, and enabling the application to produce high-quality, robust code. VTK is used world-wide in commercial applications, as well as in research and development. It is the basis for many advanced visualization applications such as ParaView, VisIt, VisTrails, Slicer, MayaVi, and OsiriX.

**Comment by nerdcha** [comment]
Thanks for the suggestion! Is this designed for interactive visualization, or is it also useful for generating static output?

**Comment by paultimothymooney** [comment]
VTK can be used for both static and interactive visualizations.

**Comment by nerdcha** [comment]
Awesome, ok, thanks!

**Pull request merged**
