### PR TITLE
Add Java 7 and H2O.

### PR DESCRIPTION
**Pull request by arnocandel**

### CODE REVIEW

**Comment by nerdcha** [comment]
Thanks very much! I'll kick off a build now and deploy it when it's ready.

**Comment by nerdcha** [comment]
@arnocandel The build hit an error with a missing public key when trying to install a dependency of `python-software-properties`. It looks like the sort of thing we ran into when installing MXNet a while ago. We cobbled together some patches for it in the MXNet section, so I'm going to try moving the h2o install after that and see how it goes.

**Comment by nerdcha** [comment]
The missing public key was fixed by re-using the `python-software-properties` install from the MXNet section. I'm removing `software-properties-common` because it seems to want to stomp over our Python installation (downgrading it to 3.4). I got a 404 on the `oracle-java7-installer` install last time, but I'll see how it goes on the next iteration.

**Comment by nerdcha** [comment]
I'm afraid we've hit the wall on the Java7 install. For some reason `apt-get` is looking in a `.../wheezy/...` location on the PPA, where I would have expected `.../trusty/...`. Here are the relevant lines of the build log:

> gpg: key EEA14886: public key "Launchpad VLC" imported
gpg: Total number processed: 1
gpg: imported: 1 (RSA: 1)
Hit http://archive.ubuntu.com trusty Release.gpg
Hit http://archive.ubuntu.com trusty Release
Hit http://archive.ubuntu.com trusty/main Sources
Hit http://archive.ubuntu.com trusty/main amd64 Packages
Hit http://security.debian.org wheezy/updates Release.gpg
Ign http://ppa.launchpad.net wheezy Release.gpg
Hit http://security.debian.org wheezy/updates Release
Ign http://ppa.launchpad.net wheezy Release
Hit http://security.debian.org wheezy/updates/main amd64 Packages
Hit http://http.debian.net wheezy-updates Release.gpg
Hit http://http.debian.net wheezy Release.gpg
Hit http://http.debian.net wheezy-updates Release
Hit http://http.debian.net wheezy Release
Get:1 http://http.debian.net wheezy-updates/main amd64 Packages/DiffIndex [367 B]
Hit http://http.debian.net wheezy/main amd64 Packages
Err http://ppa.launchpad.net wheezy/main Sources 404 Not Found
Err http://ppa.launchpad.net wheezy/main amd64 Packages 404 Not Found 
W: Failed to fetch http://ppa.launchpad.net/webupd8team/java/ubuntu/dists/wheezy/main/source/Sources 404 Not Found
W: Failed to fetch http://ppa.launchpad.net/webupd8team/java/ubuntu/dists/wheezy/main/binary-amd64/Packages 404 Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.

I guess the answer might be to tinker with the `apt-get` configuration files, though I'll have to refresh my memory of how to do that. @arnocandel Do you know a solution off the top of your head? No worries if not; I'm out of the office tomorrow but I can get back to this next week.

**Comment by nerdcha** [comment]
@arnocandel Just tried the build again — same error. Looks like some apt-get configuration changes will be needed.

**Comment by jgambera** [comment]
http://ubuntuhandbook.org/index.php/2014/02/install-oracle-java-6-7-or-8-ubuntu-14-04/

sudo add-apt-repository ppa:webupd8team/java
sudo apt-get update
sudo apt-get install oracle-java7-installer

**Comment by jgambera** [comment]
Can we validate what this image really is

FROM continuumio/anaconda3:latest

it is possible the ubuntu ppa that is called there is not able to identify the release

**Comment by jgambera** [comment]
it appears to be pure debian and not ubuntu trusty

**Comment by jgambera** [comment]
https://github.com/ContinuumIO/docker-images/blob/master/anaconda3/Dockerfile

**Comment by nerdcha** [comment]
@jgambera Oh wow, that's so weird — inside the container, `uname -a` reports Ubuntu 14.04. I didn't think to check what the base image was. Their `anaconda3` image got rebuilt only a month ago, just before we last rebuilt `kaggle/python`.

**Comment by nerdcha** [comment]
@arnocandel @jgambera Thanks for your help with this one. The rebuild of our container was briefly derailed by a couple of other packages, but we're back in action now. We've now deployed the version with your changes in it.

**Pull request merged**
