### PR TITLE
add pre-commit

### PR DESCRIPTION
**Pull request by Borda**
I may suggest use come automated formatting, for example, pre-commit, which you can also install as a [bot](https://pre-commit.ci/) that would automatically fix all open PRs. With this PR, I am just setting python check without any formatting (just adding black to config but disabling hook in the pre-commit)

### CODE REVIEW

**Comment by Borda** [comment]
just ran it locally and I would very much recommend using it as it flags several files/tests which are invalid for missing imports...
as a follow-up work, I would enable black, which would resolve all additional issues for example long lines and so on... :otter:

**Comment by Borda** [comment]
@djherbis, could you pls have a look and share your thoughts? :)

**Comment by Borda** [comment]
@djherbis is tehre anything else I can help? :rabbit:

**Comment by djherbis** [comment]
@Borda If I understand correctly, these aren't applied on the Github side, they are applied client-side (pre-commit).
This project doesn't have a lot of python code (just tests) so it's unclear to me if adding a pre-commit dependency for everyone working on this is worth it.

**Comment by djherbis** [comment]
You're more then welcome to continue to apply these in PRs you make, but I don't think it needs to be applied to all PRs made.

**Comment by Borda** [comment]
> This project doesn't have a lot of python code (just tests) so it's unclear to me if adding a pre-commit dependency for everyone working on this is worth it.

that is true, on the other hand we can stay just with general hooks and I can reduce the other :otter:

**Comment by Borda** [comment]
@djherbis could you pls have second look? :chipmunk:

**Comment by djherbis** [comment]
@Borda Hey, I still don't think we want *any* pre-commit hooks in the repo by default at this point in time.
These hooks bring in other dependencies that I don't have the bandwidth to review or decide if we want to enforce.
You're still welcome to use them for your own PRs, but I won't merge pre-commits at this time.

**Comment by djherbis** [comment]
I do still really appreciate your PRs for packages, this one just isn't something we're considering doing right now.

**Pull request closed without merging**
