### PR TITLE
Adding pytext-nlp to the kernel image

### PR DESCRIPTION
**Pull request by nlathia**
PyText has recently been open sourced by Facebook to enable faster NLP experimentation: 
https://code.fb.com/ai-research/pytext-open-source-nlp-framework/

It's likely to be super useful for all NLP competitions, such as the current Quora one:
https://www.kaggle.com/c/quora-insincere-questions-classification

Specifically, the Quora competition is a kernel submissions only *and* we cannot use internet connection enabled kernels, which is what brought me here. 

I've added the `pip install pytext-nlp` to the `Dockerfile`.

Also, I've fixed a broken URL in the `README` -- the guide was giving a 404.

### CODE REVIEW

**Comment by rosbo** [comment]
Hi,

To prevent regression in the future for this package, can you add a simple smoke test:
- https://github.com/Kaggle/docker-python#opening-a-pull-request
- https://github.com/Kaggle/docker-python/blob/master/tests/test_fastai.py

Once the some test is added, I will make sure to merge this PR promptly.

Thank you

**Comment by rosbo** [comment]
Thank you @nlathia for adding the smoke test.

**Comment by nlathia** [comment]
Thanks for merging @rosbo! I've just tried using it in a kernel, and got an import error. How long does it typically take for new libraries to become available, or did I miss something?

**Comment by rosbo** [comment]
We release a new image every other week or so. It will likely be available next week.

**Comment by nlathia** [comment]
🙌 Thank you!

**Comment by rosbo** [comment]
@nlathia `pytext-nlp` is now available in Kaggle Kernels.

**Pull request merged**
