### PR TITLE
Add magnitude

### PR DESCRIPTION
**Pull request by kklemon**
[Magnitude](https://github.com/plasticityai/magnitude) is a "fast, efficient universal vector embedding utility package".

### CODE REVIEW

**Comment by rosbo** [comment]
Have you tried following the instructions below to use this package in Kaggle Kernels?
https://github.com/Kaggle/docker-python/wiki/Missing-Packages

Let me know if it works with your package.

Thank you

**Comment by kklemon** [comment]
The problem is that I'm doing a challenge that doesn't allow custom packages or docker images. Only alternative would be, to copy the relevant code pieces into the notebook/code, but this is not very convenient.

**Comment by acsands13** [comment]
I would also appreciate adding magnitude, as it's a much faster alternative to gensim (which is already included) for loading word embeddings. Like @kklemon, I'm also using it where custom packages are not allowed.

**Comment by kklemon** [comment]
@acsands13 you are absolutely right. It's of course the `pymagnitude` package. Thanks for pointing that out.

**Comment by acsands13** [comment]
@rosbo Just curious, do these new-package requests get merged on some regularly scheduled basis? Is there anything else needed before this can be added? Thanks

**Comment by rosbo** [comment]
Hi,

To avoid regression on this package in the future, we now ask people opening a PR to add a new package to include basic smoke tests:
https://github.com/Kaggle/docker-python#opening-a-pull-request
https://github.com/Kaggle/docker-python/blob/master/tests/test_fastai.py

If you add a smoke test for this package, I will make sure to merge this PR promptly.

Thank you

**Comment by acsands13** [comment]
@rosbo @kklemon I wrote a few test cases for magnitude, which are added in #430. I also ran `./test` locally and the checks PASS.

**Comment by rosbo** [comment]
Closed in favor of PR #430.

**Pull request closed without merging**
