### PR TITLE
pip install featuretools

### PR DESCRIPTION
**Pull request by Seth-Rothschild**
This was tested on the docker image following instructions from the README. Featuretools is a library for feature engineering that is compatible with pandas and sklearn. Here's the [website](https://www.featuretools.com/) and [github repo](https://github.com/Featuretools/featuretools).

### CODE REVIEW

**Comment by nerdcha** [comment]
Looks cool, thank you!

**Comment by Seth-Rothschild** [comment]
@nerdcha That is *very* good to know. Sorry about that, we'll investigate, fix, and submit another request.

**Comment by Seth-Rothschild** [comment]
@nerdcha it looks like dropping our numpy dependency to 1.13.3 should fix this. It was 1.14.0, which is why pip was looking for a new version. We'll update in our next release and submit a PR after that.

It looks like our package also installs `pympler-0.5` and `s3fs-0.1.2` since those don't seem to be in the kernel yet. Is your preference that those lines are explicit in the dockerfile above a `pip install featuretools`, or to install them implicitly when featuretools is installed?

**Comment by nerdcha** [comment]
@Seth-Rothschild Thank you, that sounds great! We don't take a hard line against dependency imports, but given that this is a Python image, explicit would be better that implicit 😁

**Pull request merged**
