### PR TITLE
Install tensorflow-addons

### LINKED ISSUE #638: add tensorflow-addons
Would you consider adding tensorflow-addons to our image ?
 https://github.com/tensorflow/addons
It’s where most of the good pieces of functionality from tf.contrib went in TF 2.0
for example tfa.image.rotate

### PR DESCRIPTION
**Pull request by rosbo**
Fixes #638

### CODE REVIEW

**Comment by rosbo** [comment]
The test is failing with:
```
tensorflow.python.framework.errors_impl.NotFoundError: /opt/conda/lib/python3.6/site-packages/tensorflow_addons/custom_ops/activations/_activation_ops.so: undefined symbol: _ZN10tensorflow12OpDefBuilder4AttrESs
```

Based on https://github.com/tensorflow/addons/issues/574, this is because TF and TFA were built with different compilers. Because we are building TF from source to optimize it for our CPU, it creates a mismatch with the pre-built TFA binaries from pypi.

We should build TFA from source to ensure the compiler match.

**Comment by lovemeblender** [comment]
Useful change - are you guys moving forward with this?

**Comment by pairwiserr** [comment]
```
!pip install tensorflow-addons
import tensorflow_addons
```

```
NotFoundError: /opt/conda/lib/python3.6/site-packages/tensorflow_addons/custom_ops/activations/_activation_ops.so: undefined symbol: __cudaRegisterFatBinaryEnd
```

On `latest available` docker-python with `GPU` on.

**Comment by rosbo** [comment]
Yes, we are still planning to move forward with this but we will need a bit more work to build our own wheels. This is on my radar but not on top of my priority list. Hopefully, I should get to it over the next couple of weeks.

**Comment by rosbo** [comment]
Closed in favor #816

**Pull request closed without merging**
