### PR TITLE
Update Dockerfile to add Weights and Biases

### PR DESCRIPTION
**Pull request by lavanyashukla**

### CODE REVIEW

**Comment by lavanyashukla** [comment]
Hi guys! We were wondering what the reason for the jenkins failing was!
We'd be fine with just including the wandb package and not the fastparquet package!

**Comment by lavanyashukla** [comment]
Also, here's the unit test: https://github.com/Kaggle/docker-python/pull/615

**Comment by Philmod** [comment]
@lavanyashukla Could you merge the unit tests into this same PR, and also remove `fastparquet`?

**Comment by Philmod** [comment]
Closing this PR for inactivity. Feel free to reopen.

**Pull request closed without merging**
