### PR TITLE
Reduce the size of the final docker image

### PR DESCRIPTION
**Pull request by floriangeigl**
deleting various temporary/source files and clean up cache

### CODE REVIEW

**Comment by nerdcha** [comment]
This is a nice idea, thanks. I might just check that it'll still work with our favorite packages before I merge it though.

**Comment by floriangeigl** [comment]
Great! - I just experienced that pyshp currently can't be installed from pip, but they've already submitted a batch to fix that. So maybe we have to wait a few days...

**Comment by floriangeigl** [comment]
FYI: pip version of  pyshp (1.2.3) is working again.

**Comment by nerdcha** [comment]
Sorry for the delay in getting to this! Would you mind updating the PR to resolve the conflicts? I'll merge it after that.

**Comment by floriangeigl** [comment]
no worries - just made sure all pull requests (docker-python, docker-python0, 1, 2, 3) can be merged without conflict. Please note that I've moved the whole installation of opencv into one Dockerfile so we don't end up having it's installation files in one layer. (once you have them stored in a layer, removing them in later one won't reduce the final image size since layers are based on diffs)

**Pull request merged**
