### PR TITLE
Added Talos to the notebook dockerfile

### PR DESCRIPTION
**Pull request by mikkokotila**
Added [Talos](https://github.com/autonomio/talos), a package for hyperparameter optimization for Keras models.

### CODE REVIEW

**Comment by mikkokotila** [comment]
Could this be merged?

**Comment by mikkokotila** [comment]
Would you be able to merge this?

**Comment by rosbo** [comment]
Hi @mikkokotila ,

Could you add tests for this new package to prevent regression?
https://github.com/Kaggle/docker-python#opening-a-pull-request

Thank you

**Comment by rosbo** [comment]
Closing this PR for now. If you still want to add this package, please add tests as requested above to prevent regression.

To install this package in your own kernel, you can follow these instructions:
https://github.com/Kaggle/docker-python/wiki/Missing-Packages

**Pull request closed without merging**
