### PR TITLE
Added Geopandas package

### PR DESCRIPTION
**Pull request by sambozek**
Added [geopandas](http://geopandas.org/index.html) package. Pandas api to spatial data, quick way to work with spatial data using familiar api.

### CODE REVIEW

**Comment by nerdcha** [comment]
This is a great idea. Thanks! It looks like the `fiona` dependency needs `libgdal1-dev`, and a little bit of configuration to get it to load properly. I'm checking on that now. In the mean time, I think you need to make your change on a more recent version of the `kaggle/python` repo.

**Comment by sambozek** [comment]
Okay I'll update my kaggle/python fork to parity, and look into the additional dependencies as well. Thanks!

**Comment by nerdcha** [comment]
Hoo boy, the dependencies issue looks [painful](https://github.com/Toblerity/Fiona/issues/283), particularly because Toblerity are denying it's their problem. I'm sure we can figure it out though.

**Comment by antgoldbloom** [comment]
Jamie, did you end up getting geopandas in?

**Comment by antgoldbloom** [comment]
(Am interested in using for https://www.kaggle.com/antgoldbloom/gps-watch-data. Not a high priority if it's a hassle.)

**Comment by nerdcha** [comment]
@antgoldbloom I ran out of time to work on this for now, so will have to get back to it later. The linking problem with the `Fiona` dependency looks solvable, but intricate. I'd like to get it in soon, though, because `geopandas` looks great.

**Comment by nerdcha** [comment]
@sambozek Upstream updates to `Fiona` seem to have fixed the issue. I've [added it](https://github.com/Kaggle/docker-python/commit/e1e5bec8700e88b8c463e5bb4c8890fee615a402) along with geopandas to the master branch. Thanks again!

**Pull request closed without merging**
