### PR TITLE
add rgf

### PR DESCRIPTION
**Pull request by fukatani**
I want to add rgf (Regularized Greedy Forest).
Thanks!

### CODE REVIEW

**Comment by StrikerRUS** [comment]
Here are logs of successful `rgf_python` installation and tests run inside Kaggle's docker:
https://dev.azure.com/lightgbm-ci/lightgbm-ci/_build/results?buildId=689&view=logs (`Test docker` section).
Used command:
```
docker run --rm kaggle/python /bin/bash -c "pip install pytest rgf_python && git clone https://github.com/RGF-team/rgf.git && cd rgf/python-package/tests && pytest test_rgf_python.py"
```

**Comment by rosbo** [comment]
Hi @StrikerRUS,

Our goal is to provide an easy way for users to install any packages into their kernel. There is a few hurdles we have to fix before we can say that a user can install any packages without our intervention. If we can achieve this, then we will likely only include "popular" data science packages in this image where "popular" might be defined as a number of stars on GitHub or something along those lines.

Given that this package was included before, I am okay with adding it. I will add some tests to prevent regression.

**Comment by rosbo** [comment]
Added it with tests here #386.

We will share our vision and policy soon.

Stay tuned.

**Comment by StrikerRUS** [comment]
Thank you very much, @rosbo !

**Pull request closed without merging**
