### PR TITLE
Add dlib

### PR DESCRIPTION
**Pull request by irustandi**
Add dlib and easydict. Address issue #678

### CODE REVIEW

**Comment by irustandi** [comment]
Wonder why the commit failed to be built.

**Comment by Philmod** [comment]
Hi @irustandi,

There seems to be an unrelated problem in the build. I can look into it, but first, could you remove the `easydict` package, it doesn't meet our minimum requirement to be added to the common image.

Thanks,
Philippe

**Comment by irustandi** [comment]
@Philmod removed easydict. Let me know if you need anything else.

**Comment by Philmod** [comment]
Thanks @irustandi . There is an unrelated breakage I'm fixing first, then I'll check the error here.

**Comment by Philmod** [comment]
Could you merge `master` branch back into your PR? The build should be fixed.

**Comment by irustandi** [comment]
Done!

**Comment by irustandi** [comment]
Seems the build is still failing.

**Comment by Philmod** [comment]
I tested your change and it passed ci. Not sure what happened here, but I'm going to merge. Thanks for your contribution!

**Pull request merged**
