### PR TITLE
Add pyLDAvis and pattern

### PR DESCRIPTION
**Pull request by scollins83**
Adds pyLDAvis package from https://github.com/bmabey/pyLDAvis to the Dockerfile

### CODE REVIEW

**Comment by nerdcha** [comment]
Thanks, this is a great suggestion, much appreciated! And thanks for adding `pattern` too, that looks very useful.

**Comment by scollins83** [comment]
Thanks! I'm looking forward to trying out some of the mood metrics that are in pattern.en, and some of the other functions that package has.

**Comment by nerdcha** [comment]
Erm, I'm afraid I had to revert `pattern` because it didn't seem to be Python3 ready. I'll take another look at it shortly.

**Comment by nerdcha** [comment]
Seems Pattern is still a [long way off](https://github.com/clips/pattern/issues/62) 😢

**Pull request merged**
