### PR TITLE
Create adspy_shared_utilities.py

### PR DESCRIPTION
**Pull request by ayushs136**
The file is used in visualizing different classification and regression algorithms.

### CODE REVIEW

**Comment by rosbo** [comment]
Hi @ayushs136,

I suggest you add this code in your own Kaggle Kernels but we won't add this code to the base image.

Thank you

**Comment by ayushs136** [comment]
sorry, but I don't know how to do that!

**Comment by rosbo** [comment]
You can copy and paste it in the first cell of your notebook.

**Comment by ayushs136** [comment]
This is a whole package like 300 lines long
this would make my whole kernel a mess!

**Comment by rosbo** [comment]
We launched a new feature which will be useful for your use case:
https://www.kaggle.com/product-feedback/91185

**Pull request closed without merging**
