### PR TITLE
Update Dockerfile (fastai)

### PR DESCRIPTION
**Pull request by groverpr**
Please update dockerfile so that we can use fastai library for kaggle kernels. Thanks 
It's available from pip install now.

Fast.ai is deep learning and machine learning library which is developed by Jeremy Howard (and contributors). This library already has wide acceptance by people practicing deep learning and it recently came out on PyPi, especially for people who want to use it for kaggle kernels.

### CODE REVIEW

**Comment by nerdcha** [comment]
Great idea, thanks! (I moved the installation line to a block with other requested packages; the `RUN`s after that are for internal cleanup and patches.)

**Comment by groverpr** [comment]
Thanks! Can you please guide me how to use it for Kaggle kernels? I tried, 'import fastai' on kernel. It doesn't work like that. I am thinking to make a kernel to guide others also for how to use it on kaggle kernels. (who are interested to use fastai)

**Comment by nerdcha** [comment]
A guide-kernel sounds like a great idea. I haven't finished deploying the new image, but it'll be out shortly.

**Comment by nerdcha** [comment]
Thanks for your patience—the `fastai` package is ready when you are.

**Comment by groverpr** [comment]
Thanks :) So, if I just open a Jupyter notebook on Kernel, will it import `fastai` there or will I have to use `container`. 
I just tried using `'import fastai` on jupyter notebook at kernel. It doesn't work. Will I have to do this--> http://blog.kaggle.com/2016/02/05/how-to-get-started-with-data-science-in-containers/

Thanks again for guidance.

**Comment by nerdcha** [comment]
Looks like it's working to me…? https://www.kaggle.com/datacanary/fastai-check

**Comment by groverpr** [comment]
Yeah. It worked now. Probably mine was not reloaded that time. Thanks!

**Pull request merged**
