### PR TITLE
google maps API package

### PR DESCRIPTION
**Pull request by anirudhkm**
Google maps API package

### CODE REVIEW

**Comment by nerdcha** [comment]
Not seeing the point of this, since kernels don't currently have external internet access. Could you elaborate?

**Comment by anirudhkm** [comment]
Sorry, I didn't know kernels don't have internet access.

It supported requests module import, just found that though "import
requests" works fine, the methods of that module are not working.

**Comment by nerdcha** [comment]
No worries, we'll look forward to supporting that in the future.

**Comment by anirudhkm** [comment]
Also, the folium library is added to the file, but still I'm not able to
import that in kaggle kernel. Please take care on this.

**Pull request closed without merging**
