### PR TITLE
Add wandb package

### PR DESCRIPTION
**Pull request by lavanyashukla**
Hi folks!

This is an updated PR:

- adding the package wandb
- adding a test for wandb
- implementing the changes requested [here](https://github.com/Kaggle/docker-python/pull/599).

Cheers!

### CODE REVIEW

**Comment by lavanyashukla** [comment]
@Philmod could you please send me the error message for the CI? Don't have access to see it and can't run tests locally

**Comment by djherbis** [comment]
Mod is out until the new year, but it looks like the error is `AttributeError: module 'keras.backend' has no attribute '_BACKEND' ` providing I'm reading it correctly.

**Comment by rosbo** [comment]
Hi @lavanyashukla,

This error was fixed a while back. 

Run `git pull --rebase origin master` to get the latest changes. 

I also checked to confirm that our `master` branch is green so it should work after pulling assuming your changes build.

**Comment by lavanyashukla** [comment]
Thanks @rosbo, should be good to go now!

**Comment by lavanyashukla** [comment]
Hi folks! I'm trying to `import wandb` in a kaggle kernel and getting a `ModuleNotFoundError: No module named 'wandb'` error.

I tried both the 'Original' and 'Latest Available' docker images. I also tried `!pip list` and the `wandb` module doesn't show up in the list.

I was wondering how often the Dockerfile in kaggle kernels is updated and if there's another step I need to take on my end to get `wandb` into the kernel.

Thank you!
Lavanya

**Comment by rosbo** [comment]
Hi @lavanyashukla,

We haven't released a new image with this change yet. The next release is set to be the week of January 6th.

Thank you

**Comment by lavanyashukla** [comment]
Excellent, thank you!

**Comment by rosbo** [comment]
Hi @lavanyashukla,

Sad news, to avoid any disruptions with our TensorFlow 2.0 competition, we decided to postpone the release of our latest image (which includes the new 2.1 version of TensorFlow) until after it closes on January 22nd.

Sorry about the delay.

**Comment by rosbo** [comment]
After some discussions internally, given that our current image uses TensorFlow 2.1-rc0, releasing a new image with 2.1 GA isn't seen as a risk anymore. The image I was about to release included 2.1-rc2 but 2.1 GA was just released by the TensorFlow Team. I will include it before releasing a new image.

Thank you for your patience.

**Comment by lavanyashukla** [comment]
Sounds good, thank you keeping us updated @rosbo, I really appreciate it! Excited to have the wandb package in the kernel soon!

**Comment by rosbo** [comment]
`wandb` version `0.8.19` is now available in Kaggle Notebooks.

Make sure the `Docker` Settings for your notebook is set to `Latest Available` in the right panel or that your notebook was created less than 4 hours ago.

Thank you

**Comment by lavanyashukla** [comment]
Thanks so much Vincent! :) Here's a [blog post](https://www.wandb.com/articles/better-models-faster-with-weights-biases) we wrote about the integration.

**Pull request merged**
