### PR TITLE
Add chainer-chemistry

### PR DESCRIPTION
**Pull request by corochann**
Please add chainer-chemistry.
Even it is named as "chemistry", it is useful not only in chemistry field but many other data science field. 
For example, it provides `Classifier` and `Regressor` class which is useful in most of the classification/regression task with deep learning.

Link:
 - https://github.com/pfnet-research/chainer-chemistry

### CODE REVIEW

**Comment by rosbo** [comment]
Hi @corochann,

Have you tried installing it into your own kernel?

See the detailed steps: https://github.com/Kaggle/docker-python/wiki/Missing-Packages

Thank you

**Comment by corochann** [comment]
Thank you for reply.
Yes, I tried! I often use this way and thought I'm glad if I could you it from default configuration.

Also, many "kernel-only" competition prohibits to use custom docker, so I appreciate if I could you this library in kernel only comptition ([petfinder.my](https://www.kaggle.com/c/petfinder-adoption-prediction) for recent example).

**Comment by corochann** [comment]
Merged latest master & resolved conflict.

**Comment by toshi-k** [comment]
I hope this PR merged soon !
I used this package in the molecular competition and my public kernel is forked by hundreds of participants actually.
https://www.kaggle.com/toshik/schnet-starter-kit
Preinstall would improve convenience and save running time.

**Pull request merged**
