### PR TITLE
#890 Suggests tornado no longer needs pinning.

### PR DESCRIPTION
**Pull request by djherbis**
jupyter/notebook#4439 which caused this appears to be fixed

### CODE REVIEW

**Comment by rosbo** [comment]
@djherbis Have you tested this change in the notebook editor? (note: you can use the admin docker tag feature to test it out).

The jupyter notebook feature is pinned to 5.5.0 (May 2018) and likely won't include the change you are referencing.

We could consider upgrading jupyter but we would need to test that it still work with the styling and all. If we need to update the styling logic, we need to make sure that it will still works for the notebook version 5.5.0 since sessions will still be ran with it.

**Comment by djherbis** [comment]
I missed that we had notebook pinned to 5.5.0 (I had looked for 'juptyer' instead of 'notebook').

I'll still give it a test just to see, but I agree I presume it will still be broken.

**Comment by djherbis** [comment]
Yeah, this is a no-go, jupyter boots but the kernel won't.

**Comment by djherbis** [comment]
@rosbo I'm actually wondering if unpinning Jupyter might be feasible, we use static assets for jupyter now (not loaded from the actual running jupyter server in Docker), so theoretically none of those should change by unpinning jupyter itself.

**Pull request closed without merging**
