### PR TITLE
Add pytorch-lightning to Dockerfile

### PR DESCRIPTION
**Pull request by rohitgr7**
Hi, added [Pytorch Lightning](https://github.com/PyTorchLightning/pytorch-lightning/) - The lightweight PyTorch wrapper for high-performance AI research.

Lightning disentangles PyTorch code to decouple the science from the engineering by organizing it into 4 categories:
- Research code (the LightningModule).
- Engineering code (you delete, and is handled by the Trainer).
- Non-essential research code (logging, etc... this goes in Callbacks).
- Data (use PyTorch Dataloaders or organize them into a LightningDataModule).

### CODE REVIEW

**Comment by rohitgr7** [comment]
@rosbo any changes required here, or is it good?

**Comment by rosbo** [comment]
I kicked off a build on our CI server. It takes ~2 hours. We will see if we hit any dependencies issues.

**Comment by rosbo** [comment]
All green. Thanks for adding a test to prevent regression :)

**Comment by rohitgr7** [comment]
@rosbo Does it take some time for new packages to be available on Kaggle notebooks?

**Comment by rosbo** [comment]
We do a new Docker image release to Kaggle notebooks every other week. This change will land early next week. Thank you

**Pull request merged**
