### PR TITLE
Update PyTorch and Fastai to 1.0

### LINKED ISSUE #397: Updating to fastai version 1
Since the stable version of PyTorch 1.0 is released. Can we now get access to fastai version 1 of the library in Kaggle kernels?

### PR DESCRIPTION
**Pull request by rosbo**
Fixes #397

### CODE REVIEW

**Comment by arielgamino** [comment]
Yes!! Thank you!

**Comment by jaideep11061982** [comment]
i still see old evrsion when would docker images get pupdated

**Comment by arielgamino** [comment]
I created a new Kernel and see the new version. You may need to create a new Kernel.  If you created the Kernel before this merge, you will get what it was installed (fast.ai 0.7)

**Comment by rosbo** [comment]
@jaideep11061982 In Settings panel on the right, next to `Docker`. Does it say `Latest Available`? If not, you have to select it. If it does, hit the refresh button in the console panel at the bottom of your screen.

**Pull request merged**
