### PR TITLE
update pytorch-lightning to latest

### PR DESCRIPTION
**Pull request by rohitgr7**
## What does this PR do?

The issue seems to have been resolved: https://github.com/huggingface/transformers/issues/12904
so maybe now we can use latest versions of pytorch-lightning and torchmetrics. let's see if it works.

cc @rosbo

### CODE REVIEW

**Comment by rosbo** [comment]
Hi @rohitgr7,

The CPU test is failing with:

```
======================================================================
ERROR: test_pytorch_lightning (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_pytorch_lightning
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/conda/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/input/tests/test_pytorch_lightning.py", line 3, in <module>
    import pytorch_lightning as pl
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/__init__.py", line 20, in <module>
    from pytorch_lightning import metrics  # noqa: E402
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/metrics/__init__.py", line 15, in <module>
    from pytorch_lightning.metrics.classification import (  # noqa: F401
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/metrics/classification/__init__.py", line 14, in <module>
    from pytorch_lightning.metrics.classification.accuracy import Accuracy  # noqa: F401
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/metrics/classification/accuracy.py", line 16, in <module>
    from torchmetrics import Accuracy as _Accuracy
  File "/opt/conda/lib/python3.7/site-packages/torchmetrics/__init__.py", line 14, in <module>
    from torchmetrics import functional  # noqa: E402
  File "/opt/conda/lib/python3.7/site-packages/torchmetrics/functional/__init__.py", line 14, in <module>
    from torchmetrics.functional.audio.pit import pit, pit_permutate
  File "/opt/conda/lib/python3.7/site-packages/torchmetrics/functional/audio/__init__.py", line 14, in <module>
    from torchmetrics.functional.audio.pit import pit, pit_permutate  # noqa: F401
  File "/opt/conda/lib/python3.7/site-packages/torchmetrics/functional/audio/pit.py", line 22, in <module>
    from torchmetrics.utilities.imports import _SCIPY_AVAILABLE
  File "/opt/conda/lib/python3.7/site-packages/torchmetrics/utilities/imports.py", line 83, in <module>
    _TRANSFORMERS_AVAILABLE: bool = _module_available("transformers")
  File "/opt/conda/lib/python3.7/site-packages/torchmetrics/utilities/imports.py", line 33, in _module_available
    return find_spec(module_path) is not None
  File "/opt/conda/lib/python3.7/importlib/util.py", line 114, in find_spec
    raise ValueError('{}.__spec__ is None'.format(name))
ValueError: transformers.__spec__ is None
```

You can download the built image to play with by running:

```
docker pull gcr.io/kaggle-images/python:PR-1087-pretest
docker run -it --rm gcr.io/kaggle-images/python:PR-1087-pretest /bin/bash
```

You can then run the failing test with:

```
cd /to/git/docker-python/ # varies based on where you checked out the repo
./test -i docker pull gcr.io/kaggle-images/python:PR-1087-pretest -p test_pytorch_lightning.py
```

**Comment by rohitgr7** [comment]
hey @rosbo 
allen-nlp released a new version recently. the packages must have been updated. Can you re-run the ci tests??

**Comment by rosbo** [comment]
@rohitgr7, can you rebase your branch first to get the latest changes from `main`. Thank you

**Comment by rohitgr7** [comment]
@rosbo done!

**Comment by rohitgr7** [comment]
same error?

**Comment by rosbo** [comment]
Looks like our `main` branch started failing on a protobuf version issue yesterday. This branch is not failing with the same error. I will fix `main`.

**Comment by rosbo** [comment]
@rohitgr7 `main` is green again. If you update your branch to get the latest changes, it should hopefully pass.

**Comment by rohitgr7** [comment]
@rosbo done!

**Comment by rohitgr7** [comment]
its failing. Can you share the error ? @rosbo

**Comment by kaushikb11** [comment]
Hey @rosbo, could you help us the error trace? The is a priority as lot of our users would like to use the latest lightning version on Kaggle.

**Comment by rosbo** [comment]
Hi @kaushikb11,

With this change, the tests are now hanging: `./test -i gcr.io/kaggle-images/python:pl_latest-pretest`.

I started looking into it yesterday but was not able to get down to the root cause.

**Comment by tchaton** [comment]
Dear @rosbo,

Anything we could do to help debug this? Any chance we could get the trace in private PM?

Best,
T.C

**Comment by rosbo** [comment]
@tchaton you can clone this repo and run the following command inside the checked-out directory:

```
cd path/to/git/docker-python
./test -i gcr.io/kaggle-images/python:pl_latest-pretest
```

You will see that the tests are hanging.

**Comment by rosbo** [comment]
I think I may have found the culprit: https://github.com/Kaggle/docker-python/pull/1102

**Comment by kaushikb11** [comment]
I ran the tests last night, it was hanging at this point

```python
test_monkeypatching_idempotent (test_translation.TestCloudTranslation) ... ok
test_monkeypatching_succeed (test_translation.TestCloudTranslation) ... ok
test_user_provided_credentials_v2 (test_translation.TestCloudTranslation) ... ok
test_user_provided_credentials_v3 (test_translation.TestCloudTranslation) ... ok
Feature Extraction: 100%|█████████████████████████|
```

**Comment by rosbo** [comment]
^ It hangs at the same spot on CI.

If I run only the `test_tsfresh.py` test, than it passes.
If I run only the `test_pytorch_lightning` test, it passes also.

But running both of them together fails.

Looks like a shared object loading mistmatch is the culprit. 

```
> LD_DEBUG=libs python -c 'import pytorch_lightning' 2>&1 | grep libstdc++
...
calling fini: /usr/lib/x86_64-linux-gnu/libstdc++.so.6

> LD_DEBUG=libs python -c 'import tsfresh' 2>&1 | grep libstdc++
...
calling fini: /opt/conda/lib/python3.7/site-packages/pyarrow/../../../libstdc++.so.6
# normalized path: /opt/conda/lib/libstdc++.so.6
```

Basically, `tsfresh` doesn't work with the version of libstdc++ at /usr/lib/x86_64-linux-gnu but only at /opt/conda/lib. If `pytorch_lightning` is imported before `tsfresh`, then libstdc++ is already loaded and `tsfresh` fails with the version loaded for `pytorch_lightning`.

Comparing `libstdc++` versions:

```
> ls /usr/lib/x86_64-linux-gnu/ | grep libstdc++
libstdc++.so.6
libstdc++.so.6.0.25
> ls /opt/conda/lib/ | grep libstdc++
libstdc++.so
libstdc++.so.6
libstdc++.so.6.0.29
```

Running the unit test in full isolation is one way to solve it. However, some packages (not these two) are often used together and should work together and we wouldn't test that anymore...

**Comment by kaushikb11** [comment]
Noted! Should we run the unit test in isolation then? As lightning and tsfresh often wouldn't be used together

**Comment by rosbo** [comment]
I upgraded the base image to `m87` in #1110. This includes a newer version of `libstdc++` (6.0.28) which solves the issue.

**Comment by rohitgr7** [comment]
Thanks a lot @rosbo 😃

**Pull request merged**
