### PR TITLE
Bump PyTorch version to 2.2

### PR DESCRIPTION
**Pull request by will-cromar**
Also bump ecosystem packages (`torchtext`, `torchvision`, `torchaudio`) to latest versions

### CODE REVIEW

**Comment by will-cromar** [comment]
cc @djherbis

**Comment by djherbis** [comment]
Thanks!

**Comment by will-cromar** [comment]
It looks like `TPU_LIBRARY_PATH` is getting overridden to the libtpu package: 

image

In the 2.2 release, we intentionally don't write that value, but we do treat it as an override: https://github.com/pytorch/xla/blob/v2.2.0/torch_xla/__init__.py#L98-L125

**Comment by djherbis** [comment]
Looks like this is the actual cause of the failure:
```
#13 90.98 ERROR: Cannot install torch==2.2.0 and torchvision==0.17.1 because these package versions have conflicting dependencies.

#13 90.98 

#13 90.98 The conflict is caused by:

#13 90.98     The user requested torch==2.2.0

#13 90.98     torchvision 0.17.1 depends on torch==2.2.1
```

@will-cromar Can we use 2.2.1?

**Comment by djherbis** [comment]
Trying 2.2.1: https://github.com/Kaggle/docker-python/commit/da1e2ec3b107c6dc9d4746eab75f6774f8be83e3

**Comment by will-cromar** [comment]
> Trying 2.2.1: [da1e2ec](https://github.com/Kaggle/docker-python/commit/da1e2ec3b107c6dc9d4746eab75f6774f8be83e3)

2.2.1 won't work because `torch_xla` hasn't published a corresponding patch release. What you can do is keep `2.2.0` in the config, then switch the `torch==${TORCH_VERSION}` for `torch~=${TORCH_VERSION}`. This will install the latest patch release for torch under 2.2.

**Comment by djherbis** [comment]
Thanks, trying that: https://github.com/Kaggle/docker-python/pull/1365

**Comment by djherbis** [comment]
Nice, it builds at least :)

**Pull request merged**
