### PR TITLE
upgrade nodejs and npm

### PR DESCRIPTION
**Pull request by peijenlin**
* nodejs version 12.x
* npm version latest

### CODE REVIEW

**Comment by djherbis** [comment]
Do these need to be installed in the image served to users? Or should this image just be used as the base image for your dev stuff?

**Comment by peijenlin** [comment]
This is required for installing the extension on prod eventually.

**Comment by rosbo** [comment]
If you think you may have a lot of packages to install (and test various versions and so on), you can work on your own branch. This way, you won't need to have to wait for our review until you know exactly which package you need. The ci server will build an image for you: https://ci.kaggle.net/job/kernels/job/docker-python/

The name of the image will be gcr.io/kaggle-images/python:<branch-name>-staging.

**Comment by peijenlin** [comment]
Yes, I already have that for the dev docker image, but this will need to go into the official images before we roll out the extension.

**Comment by rosbo** [comment]
Do you foresee having to add other packages to the official image? Consider waiting and opening a PR with all the packages you need. If this is the only package you need, then, I am fine with going ahead and merging it.

**Comment by djherbis** [comment]
Please re-add me to review once we're closer to ready for this.

**Comment by Philmod** [comment]
Is this still necessary or could we close the PR?

**Pull request closed without merging**
