### PR TITLE
Add Support for FastAI 2

### PR DESCRIPTION
**Pull request by avn3r**
Include both fastai and fastai2 so users can use either version of the library. This will allow old users to use the older library and new users to use the newer library (fastai2)

### CODE REVIEW

**Comment by rosbo** [comment]
> NB: This is still in early development. Use v1 unless you want to contribute to the next version of fastai

I would suggest we wait until this reaches a more stable state before adding this to all Kaggle Kernels.

For the time being, users can run `!pip install fastai2` in an internet-enabled notebook.

**Comment by avn3r** [comment]
Thanks yes I am using your suggestion currently. It's been in development for a while but yeah for some reason they just never officially release it lol. On a completely different note, do you know how put add arguments or parameters to `kaggle kernels push`. I would like to do `kaggle kernels push --alpha 0.9` something like that.

**Comment by harrisse** [comment]
@avn3r I believe the only parameters we support for kernels push through the API are `-p` for path and `-h` for help. Other parameters for the request can be set in the kernel-metadata.json file as described here: https://github.com/Kaggle/kaggle-api#push-a-kernel. What are you looking to do?

**Comment by avn3r-dn** [comment]
Yeah that' what the API mentions I want to be able to pass parameters that can be accessed from the notebook to have variable runs. basically `kaggle kernels push --args values` and then read them on the notebook. Or pass additional key value pairs in the metada.json and be able to access them on kaggle. Right now my notebooks are fix, adding these arguments will allow me to make them dynamic. Basically I want an argparser from the cli that can be accessed in the notebook. Or a way to pass a config.yml so that can be read by the notebook.

Regards and thanks for listening.

**Comment by harrisse** [comment]
We don't support that model, but I'd recommend instead including variables like that in your source code directly since each kernel push is associated with a code file.

**Comment by rosbo** [comment]
Closing this PR for now. Let's wait until fastai 2 reaches GA.

**Pull request closed without merging**
