### PR TITLE
Add neon

### PR DESCRIPTION
**Pull request by anlthms**

### CODE REVIEW

**Comment by nerdcha** [comment]
Great! Thanks for suggesting this.

**Comment by anlthms** [comment]
Hi Jamie,
Thanks for merging this change. I added an example script:
https://www.kaggle.com/anlthms/digit-recognizer/quick-shallow-mlp-with-neon

**Comment by nerdcha** [comment]
Sorry about that — the new nightly of OpenCV is breaking our build a little bit downstream of your change. I'm hoping to have that fixed shortly.

**Comment by nerdcha** [comment]
neon and OpenCV are now both building correctly and have been deployed to our Scripts worker machines. Thanks again for the contribution! Looking forward to seeing neon in action.

**Comment by anlthms** [comment]
Great! We had an issue on our side with python3 compatibility. Fixed now in the neon repository. After a rebuild, the example script should start working.

**Comment by nerdcha** [comment]
All set! The latest neon build is deployed, and I checked that your script works now — but only if you drop the size of the hidden layer a little (I used 1000 nodes). Currently we limit script execution to 10 minutes runtime and 2Gb memory, and with 3000 nodes the script hits one or both of those limits.

**Pull request merged**
